services:
    app.form.registration:
        class: HotelBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    HotelBundle\Service\FileUploader:
      arguments:
        $targetDir: '%image_directory'