<?php

namespace HotelBundle\Repository;
use Doctrine\ORM\Query\ResultSetMappingBuilder;
use HotelBundle\Entity\Media;
use Doctrine\DBAL;

/**
 * RoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomRepository extends \Doctrine\ORM\EntityRepository
{
    // $conn instanceof Doctrine\DBAL\Connection
    public function getThinggie($obtained)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c.imageUrl FROM HotelBundle:Room p 
                      JOIN HotelBundle:Media c
                      WHERE c.room = p.id
                      WHERE p.id = '.$obtained
            )
            ->getResult()[0];
    }

    public function deleteThinggie($obtained)
    {
        return $this->getEntityManager()
            ->createQuery(
                'DELETE c.imageUrl FROM HotelBundle:Room p 
                      JOIN HotelBundle:Media c
                      WHERE c.room = p.id
                      WHERE p.id = '.$obtained
            )
            ->execute();
    }
}
